name: Docker to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest

    - name: Deploy on NCP Server
      uses: appleboy/ssh-action@v1.0.3
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        host: ${{ secrets.NCP_SERVER_IP }}
        username: root
        key: ${{ secrets.NCP_SERVER_KEY }}
        port: 22
        envs: DOCKERHUB_USER,DOCKERHUB_PASS
        script: |
          echo "$DOCKERHUB_PASS" | sudo docker login -u "$DOCKERHUB_USER" --password-stdin
          
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest
          sudo docker stop nodejs-container || true
          sudo docker rm nodejs-container || true
          sudo docker run -d --name nodejs-container -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest
          sudo docker image prune -f